version: '3.6'
services:
    app:
        build: .
        environment:
            - NODE_ENV=development
            - MONGODB_URI=mongodb://mongo:27017
        command: npm start
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: "mongo:3.4.1"
        ports:
          - '27017:27017'
        volumes:
          - 'mongo:/data/db'
volumes:
    mongo:
